### ISSUE TITLE
pip install doesn't install migrations

### ISSUE THREAD

**Issue by jthigpen** [waterimp/django-single-table-db-storage#3]
disclaimer: I don't grok python packaging.

HOWEVER,

When I installed this app via pip, the migrations file didn't copy over.

```
(.venv) jamesthigpen@Jamess-MacBook-Air django_single_table_db_storage % ls -la
total 32
drwxr-xr-x   8 jamesthigpen  staff   256 Jan 22 08:19 .
drwxr-xr-x  44 jamesthigpen  staff  1408 Jan 22 08:09 ..
-rw-r--r--   1 jamesthigpen  staff     0 Jan 22 08:09 __init__.py
drwxr-xr-x   7 jamesthigpen  staff   224 Jan 22 08:09 __pycache__
-rw-r--r--   1 jamesthigpen  staff   700 Jan 22 08:09 models.py
-rw-r--r--   1 jamesthigpen  staff  2288 Jan 22 08:09 storage.py
-rw-r--r--   1 jamesthigpen  staff   165 Jan 22 08:09 urls.py
-rw-r--r--   1 jamesthigpen  staff   640 Jan 22 08:09 views.py
(.venv) jamesthigpen@Jamess-MacBook-Air django_single_table_db_storage % pwd
/Users/jamesthigpen/Documents/commissioneer/.venv/lib/python3.11/site-packages/django_single_table_db_storage
(.venv) jamesthigpen@Jamess-MacBook-Air django_single_table_db_storage % 
```

I copied the migrations folder out of the git repo and they ran fine and everything worked great. I looked at the setup.py and nothing _seemed_ obviously wrong but I also probably woudln't know better. 

Thanks for this project, it's exactly what I needed this morning. You're my hero of the day.

**Comment by jthigpen** [comment]
https://stackoverflow.com/questions/29609141/why-doesnt-setuptools-copy-modules-in-a-subfolder
It looks like `packages` is pretty literal in setup.py.

I guess `find_packages` is a thing, but also that's from 2017 and the setuptools docs are confusing if that's still the thing to do. :(

https://setuptools.pypa.io/en/latest/setuptools.html

**Comment by waterimp** [comment]
@jthigpen - Thank you for reporting the issue and sharing some ideas on a fix. The issue should be fixed now. If you upgrade to version 0.1.3, you should no longer have to manually copy the migrations. Please let me know if you still have issues.

```shell
pip install django-single-table-db-storage==0.1.3
```

**Comment by jthigpen** [comment]
@waterimp Thank you!
